name: ethionutri_mobile
description: "AI-powered Ethiopian Nutrition and Fasting Mobile App"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.5.5
  image_picker: ^1.2.3
  intl: ^0.20.3
  url_launcher: ^6.3.2
  jitsi_meet_flutter_sdk: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true