/**
 * Authentic FAO & Ethiopian Public Health Institute (EPHI) Food Composition Dataset
 * Values represent 100g edible portions of traditional Ethiopian foods & ingredients.
 */

const FAO_ETHIOPIAN_FOODS = [
  {
    name: 'Teff Injera (White / Nech Teff)',
    nameAmharic: 'ነጭ ቴፍ እንጀራ',
    category: 'Grains & Bread',
    caloriesPer100g: 155.0,
    proteinGrams: 4.8,
    carbsGrams: 32.5,
    fatsGrams: 0.7,
    ironMg: 14.2, // High bioavailable iron in Teff
    zincMg: 2.1,
    calciumMg: 156.0,
    b12Mcg: 0.0,
    isVegan: true,
    isTraditional: true,
    faoReference: 'FAO-EPHI Table Food ID ET-01-001 (Teff fermented bread)'
  },
  {
    name: 'Teff Injera (Red / Key Teff)',
    nameAmharic: 'ቀይ ቴፍ እንጀራ',
    category: 'Grains & Bread',
    caloriesPer100g: 148.0,
    proteinGrams: 5.1,
    carbsGrams: 30.8,
    fatsGrams: 0.8,
    ironMg: 18.5, // Exceptionally high iron content in Red Teff
    zincMg: 2.4,
    calciumMg: 180.0,
    b12Mcg: 0.0,
    isVegan: true,
    isTraditional: true,
    faoReference: 'FAO-EPHI Table Food ID ET-01-002'
  },
  {
    name: 'Shiro Wat (Chickpea & Pea Stew)',
    nameAmharic: 'ሽሮ ወጥ',
    category: 'Stews & Legumes',
    caloriesPer100g: 125.0,
    proteinGrams: 7.2,
    carbsGrams: 16.4,
    fatsGrams: 3.8,
    ironMg: 4.6,
    zincMg: 1.5,
    calciumMg: 68.0,
    b12Mcg: 0.0,
    isVegan: true, // Standard Tsom food
    isTraditional: true,
    faoReference: 'FAO-EPHI Table Food ID ET-03-014 (Chickpea flour stew)'
  },
  {
    name: 'Shiro Tegabino (Thick Clay-Pot Shiro)',
    nameAmharic: 'ሽሮ ተጋቢኖ',
    category: 'Stews & Legumes',
    caloriesPer100g: 145.0,
    proteinGrams: 8.5,
    carbsGrams: 18.2,
    fatsGrams: 4.5,
    ironMg: 5.8,
    zincMg: 1.8,
    calciumMg: 75.0,
    b12Mcg: 0.0,
    isVegan: true,
    isTraditional: true,
    faoReference: 'FAO-EPHI Table Food ID ET-03-015'
  },
  {
    name: 'Misir Wat (Spicy Red Lentil Stew)',
    nameAmharic: 'ምስር ወጥ',
    category: 'Stews & Legumes',
    caloriesPer100g: 138.0,
    proteinGrams: 8.9,
    carbsGrams: 19.5,
    fatsGrams: 3.2,
    ironMg: 6.2,
    zincMg: 1.7,
    calciumMg: 42.0,
    b12Mcg: 0.0,
    isVegan: true,
    isTraditional: true,
    faoReference: 'FAO-EPHI Table Food ID ET-03-008 (Lentils stew with berbere)'
  },
  {
    name: 'Kik Alicha (Yellow Split Pea Stew)',
    nameAmharic: 'ክክ አልጫ ወጥ',
    category: 'Stews & Legumes',
    caloriesPer100g: 118.0,
    proteinGrams: 7.8,
    carbsGrams: 17.1,
    fatsGrams: 2.1,
    ironMg: 3.8,
    zincMg: 1.4,
    calciumMg: 45.0,
    b12Mcg: 0.0,
    isVegan: true,
    isTraditional: true,
    faoReference: 'FAO-EPHI Table Food ID ET-03-010'
  },
  {
    name: 'Gomen (Collard Greens with Spices)',
    nameAmharic: 'ጎመን ወጥ',
    category: 'Vegetables',
    caloriesPer100g: 65.0,
    proteinGrams: 2.8,
    carbsGrams: 8.2,
    fatsGrams: 2.5,
    ironMg: 2.8,
    zincMg: 0.6,
    calciumMg: 145.0,
    b12Mcg: 0.0,
    isVegan: true,
    isTraditional: true,
    faoReference: 'FAO-EPHI Table Food ID ET-04-003 (Ethiopian Kale / Collard)'
  },
  {
    name: 'Atkilt Wat (Cabbage, Carrots & Potatoes)',
    nameAmharic: 'አትክልት ወጥ',
    category: 'Vegetables',
    caloriesPer100g: 78.0,
    proteinGrams: 2.1,
    carbsGrams: 12.4,
    fatsGrams: 2.4,
    ironMg: 1.4,
    zincMg: 0.5,
    calciumMg: 38.0,
    b12Mcg: 0.0,
    isVegan: true,
    isTraditional: true,
    faoReference: 'FAO-EPHI Table Food ID ET-04-012'
  },
  {
    name: 'Doro Wat & Egg (Chicken Stew)',
    nameAmharic: 'ዶሮ ወጥ',
    category: 'Poultry & Meat',
    caloriesPer100g: 220.0,
    proteinGrams: 18.5,
    carbsGrams: 6.2,
    fatsGrams: 13.8,
    ironMg: 3.2,
    zincMg: 2.9,
    calciumMg: 35.0,
    b12Mcg: 1.8, // Contains B12
    isVegan: false, // Non-Tsom food
    isTraditional: true,
    faoReference: 'FAO-EPHI Table Food ID ET-08-001 (Spicy Chicken Stew)'
  },
  {
    name: 'Suf Fitfit (Sunflower Seed Juice Dip with Injera)',
    nameAmharic: 'ሱፍ ፍትፍት',
    category: 'Traditional Fasting Dishes',
    caloriesPer100g: 185.0,
    proteinGrams: 6.5,
    carbsGrams: 24.2,
    fatsGrams: 7.8,
    ironMg: 5.2,
    zincMg: 2.0,
    calciumMg: 82.0,
    b12Mcg: 0.0,
    isVegan: true,
    isTraditional: true,
    faoReference: 'FAO-EPHI Table Food ID ET-05-004'
  },
  {
    name: 'Telba Fitfit (Flaxseed Hydration Dip with Injera)',
    nameAmharic: 'ተልባ ፍትፍት',
    category: 'Traditional Fasting Dishes',
    caloriesPer100g: 192.0,
    proteinGrams: 7.1,
    carbsGrams: 22.8,
    fatsGrams: 9.1, // Rich in Omega-3 Alpha-Linolenic Acid
    ironMg: 5.8,
    zincMg: 2.3,
    calciumMg: 110.0,
    b12Mcg: 0.0,
    isVegan: true,
    isTraditional: true,
    faoReference: 'FAO-EPHI Table Food ID ET-05-006'
  },
  {
    name: 'Bulla Porridge / Genfo',
    nameAmharic: 'ቡላ ገንፎ',
    category: 'Grains & Porridge',
    caloriesPer100g: 165.0,
    proteinGrams: 1.8,
    carbsGrams: 38.5,
    fatsGrams: 1.2,
    ironMg: 3.1,
    zincMg: 0.8,
    calciumMg: 120.0,
    b12Mcg: 0.0,
    isVegan: true,
    isTraditional: true,
    faoReference: 'FAO-EPHI Table Food ID ET-01-022 (Enset starch porridge)'
  },
  {
    name: 'Kolo (Roasted Barley & Chickpea Snack)',
    nameAmharic: 'ቆሎ',
    category: 'Snacks',
    caloriesPer100g: 380.0,
    proteinGrams: 12.8,
    carbsGrams: 64.0,
    fatsGrams: 6.5,
    ironMg: 6.8,
    zincMg: 3.2,
    calciumMg: 95.0,
    b12Mcg: 0.0,
    isVegan: true,
    isTraditional: true,
    faoReference: 'FAO-EPHI Table Food ID ET-01-015'
  }
];

module.exports = { FAO_ETHIOPIAN_FOODS };
